---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/rajkumar/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/rajkumar
    - name : Build image
      command: docker build -t rajkumar167r/mavenwebapp .
    - name : Push Docker Image
      command: docker push rajkumar167r/mavenwebapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: 
     copy:
       src: k8s-deploy.yml
       dest: /home/rajkumar
   - name : K8S Deployment
     command: kubectl apply -f k8s-deploy.yml
